/**
 * Keep a union's games from a WebSports ball-by-ball export, for the scouting dashboard.
 *
 *   npx tsx scripts/websports-for-union.ts <websports.csv> <union-results.csv> <out-dir> <slug> [union]
 *
 * A side belongs to the union when its club or school played 10+ league games in the union's
 * own results export this season (so a touring side that met it once is an opponent). Writes,
 * into <out-dir> (keep it inside the git-ignored src/scouting-local/):
 *   - websports/<slug>.csv — the ball-by-ball rows of every game a union side played;
 *   - websports-<slug>.ts  — the scouting event built from them, naming the union's sides.
 * Real names are in both, which is why they belong in scouting-local and nowhere else.
 */
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { clubName, parseResults } from '../src/pathways';
import { csvRows } from '../src/pathways';

const [src, results, outDir, slug, union = 'Gauteng'] = process.argv.slice(2);
if (!src || !results || !outDir || !slug) {
  console.error(
    'usage: websports-for-union.ts <websports.csv> <union-results.csv> <out-dir> <slug> [union]',
  );
  process.exit(1);
}

const norm = (s: string) => s.toLowerCase().replace(/[^a-z]/g, '');
export const MIN_LEAGUE_GAMES = 10;

// The union's own clubs and schools: 10+ league games in its results this season.
const games = new Map<string, number>();
for (const m of parseResults(readFileSync(results, 'utf8')))
  if (m.type === 'league' && m.tier !== 'representative')
    for (const s of m.sides) games.set(norm(s.club), (games.get(norm(s.club)) ?? 0) + 1);
const ours = (team: string) => (games.get(norm(clubName(team))) ?? 0) >= MIN_LEAGUE_GAMES;

const text = readFileSync(src, 'utf8');
const rows = csvRows(text);
const head = rows[0];
const ix = (k: string) => head.indexOf(k);
const [cGame, cBat, cFld] = [ix('GameID'), ix('BattingTeam'), ix('BowlingTeam')];
const keepGames = new Set<string>();
const sides = new Set<string>();
for (const r of rows.slice(1))
  for (const t of [r[cBat], r[cFld]])
    if (t && ours(t)) {
      keepGames.add(r[cGame]);
      sides.add(t);
    }

const q = (v: string) => (/[",\n]/.test(v) ? `"${v.replace(/"/g, '""')}"` : v);
const kept = rows.slice(1).filter((r) => keepGames.has(r[cGame]));
mkdirSync(join(outDir, 'websports'), { recursive: true });
writeFileSync(
  join(outDir, 'websports', `${slug}.csv`),
  [head, ...kept].map((r) => r.map(q).join(',')).join('\n'),
);
writeFileSync(
  join(outDir, `websports-${slug}.ts`),
  `// Generated by scripts/websports-for-union.ts — ${union} sides' games from WebSports. Local only.
import csv from './websports/${slug}.csv?raw';
import { eventFromMatches } from '../scouting-build';
import { parseWebSports } from '../websports';

export default eventFromMatches(
  {
    id: 'websports-${slug}',
    name: 'WebSports 2026 — ${union} sides',
    ageGroup: 'U19',
    source: 'WebSports Match Centre, ball by ball',
    union: ${JSON.stringify(union)},
    ourTeams: ${JSON.stringify([...sides].sort())},
  },
  parseWebSports(csv),
);
`,
);
console.log(
  `${keepGames.size} games, ${kept.length} balls, ${sides.size} ${union} side(s) → ${join(outDir, 'websports', slug + '.csv')}`,
);
