/* ─── Fixtures & Venues → Leagues & tournaments (ADR 0018) ───
 *
 * The competitions table (one row per league, tournament, operator season or imported
 * schedule), "Create league" / "Create tournament" (the draw is generated by the server and
 * previewed before anything is saved), and one competition's views: Fixtures (the existing
 * editor and release bar), Table, Results matrix, Home/away, and Settings (rename, points,
 * regenerate, delete). The league catalogue lives here too, beside the competitions.
 */
import { useMemo, useState, type ReactNode } from 'react';
import * as api from './api';
import { ApiError } from './api';
import { Btn, Modal } from './atoms';
import { SeriesOriginPill } from './season-run';
import type { Series } from './types';
import {
  groupCompetitions,
  homeAwayBalance,
  resultsMatrix,
  seriesStandings,
  sideName,
  teamNames,
  type CmpFixture,
  type CmpRun,
  type CmpSeries,
  type CompetitionGroup,
} from './competitions';
import type { CompetitionFormat, CompetitionMeta } from '../packages/engine/src/competition';
import { clubTeamsForLeague } from '../packages/engine/src/leagues';
import { DEFAULT_CRICKET_POINTS, type PointsRules } from '../packages/engine/src/standings';

const fmtDay = (d?: string) =>
  d
    ? new Date(`${d}T00:00:00Z`).toLocaleDateString('en-GB', {
        day: 'numeric',
        month: 'short',
        year: 'numeric',
        timeZone: 'UTC',
      })
    : '—';
const errText = (e: unknown) =>
  !(e instanceof ApiError)
    ? 'Could not reach the server — check your connection.'
    : e.status === 404
      ? 'That league or tournament is no longer there (or the server is out of date). Refresh the page.'
      : ((e.details?.problems as string[] | undefined)?.join(' ') ?? e.message);

interface ClubLike {
  id: string;
  name: string;
  leagues?: string[];
  leagueTeams?: Record<string, number>;
  teamRosters?: Record<string, unknown>;
  ground?: { venue?: string; lat?: number; lon?: number };
}
interface LeagueLike {
  key: string;
  label: string;
}

export interface CompetitionsPanelProps {
  allSeries: CmpSeries[];
  clubs: ClubLike[];
  leagues: LeagueLike[];
  runs: CmpRun[];
  /** The selected series (the editor shows it). */
  activeId?: string;
  onSelectSeries: (id: string) => void;
  /** The existing fixture editor + release bar for the selected series. */
  renderFixtures: () => ReactNode;
  /** The league catalogue (AdminLeagues, embedded). */
  catalogue?: ReactNode;
  /** The operator's seasons panel (SeasonRunsPanel). */
  seasons?: ReactNode;
  /** The selected series' status pills (Draft / Released / Withheld … / Activates …). */
  renderStatus?: () => ReactNode;
  onChanged: () => void;
  toast: (m: string, tone?: string) => void;
}

/* ─── The page ─── */

export function CompetitionsPanel(p: CompetitionsPanelProps) {
  const leagueLabel = (k: string) => p.leagues.find((l) => l.key === k)?.label ?? k;
  const groups = useMemo(
    () => groupCompetitions(p.allSeries, p.runs, leagueLabel),
    // eslint-disable-next-line react-hooks/exhaustive-deps
    [p.allSeries, p.runs, p.leagues],
  );
  const [view, setView] = useState<'list' | 'catalogue'>('list');
  const [openKey, setOpenKey] = useState<string | null>(() => {
    const g = groups.find((x) => x.series.some((s) => s.id === p.activeId));
    return typeof window !== 'undefined' &&
      new URLSearchParams(window.location.search).get('series')
      ? (g?.key ?? null)
      : null;
  });
  const [dialog, setDialog] = useState<
    | null
    | { mode: 'create'; type: 'league' | 'tournament' }
    | { mode: 'regenerate'; group: CompetitionGroup }
  >(null);
  const open = groups.find((g) => g.key === openKey) ?? null;

  // The open competition rides on `?series=` so a reload or a link lands on it.
  const syncUrl = (seriesId: string | null) => {
    if (typeof window === 'undefined') return;
    const url = new URL(window.location.href);
    if (seriesId) url.searchParams.set('series', seriesId);
    else url.searchParams.delete('series');
    window.history.replaceState(window.history.state, '', url);
  };
  const openGroup = (g: CompetitionGroup) => {
    setOpenKey(g.key);
    const id = g.series.some((s) => s.id === p.activeId) ? p.activeId! : g.series[0].id;
    if (id !== p.activeId) p.onSelectSeries(id);
    syncUrl(id);
  };

  return (
    <div className="cmp">
      {open ? (
        <CompetitionDetail
          {...p}
          group={open}
          onBack={() => {
            setOpenKey(null);
            syncUrl(null);
          }}
          onRegenerate={() => setDialog({ mode: 'regenerate', group: open })}
          onDeleted={() => {
            setOpenKey(null);
            syncUrl(null);
          }}
        />
      ) : (
        <>
          <div className="cmp-head">
            <div className="cmp-seg" role="tablist" aria-label="Leagues and tournaments">
              <button
                role="tab"
                aria-selected={view === 'list'}
                className={view === 'list' ? 'on' : ''}
                onClick={() => setView('list')}
              >
                Competitions <span className="cmp-n">{groups.length}</span>
              </button>
              {p.catalogue && (
                <button
                  role="tab"
                  aria-selected={view === 'catalogue'}
                  className={view === 'catalogue' ? 'on' : ''}
                  onClick={() => setView('catalogue')}
                >
                  League catalogue <span className="cmp-n">{p.leagues.length}</span>
                </button>
              )}
            </div>
            {view === 'list' && (
              <div className="fh-toolbar-right">
                <Btn
                  tone="outline"
                  size="sm"
                  onClick={() => setDialog({ mode: 'create', type: 'tournament' })}
                >
                  + Create tournament
                </Btn>
                <Btn
                  tone="ink"
                  size="sm"
                  onClick={() => setDialog({ mode: 'create', type: 'league' })}
                >
                  + Create league
                </Btn>
              </div>
            )}
          </div>
          {view === 'catalogue' ? (
            p.catalogue
          ) : (
            <>
              <CompetitionsTable groups={groups} onOpen={openGroup} />
              {p.seasons && (
                // Open whenever a season is running (it is where its stages are worked
                // through); remounts open the moment the first one starts.
                <details
                  key={p.runs.length > 0 ? 'running' : 'none'}
                  className="cmp-seasons"
                  open={p.runs.length > 0}
                >
                  <summary>Seasons set up by your operator</summary>
                  {p.seasons}
                </details>
              )}
            </>
          )}
        </>
      )}
      {dialog && (
        <CompetitionDialog
          mode={dialog.mode}
          type={dialog.mode === 'create' ? dialog.type : (dialog.group.meta?.type ?? 'league')}
          group={dialog.mode === 'regenerate' ? dialog.group : undefined}
          clubs={p.clubs}
          leagues={p.leagues}
          onClose={() => setDialog(null)}
          onDone={(id, firstSeriesId, message) => {
            setDialog(null);
            p.onChanged();
            p.toast(message);
            setOpenKey(`c:${id}`);
            p.onSelectSeries(firstSeriesId);
            syncUrl(firstSeriesId);
          }}
        />
      )}
    </div>
  );
}

/* ─── The competitions table ─── */

function CompetitionsTable({
  groups,
  onOpen,
}: {
  groups: CompetitionGroup[];
  onOpen: (g: CompetitionGroup) => void;
}) {
  if (!groups.length)
    return (
      <div className="fh-empty">
        No leagues or tournaments yet. Create one above — the fixtures are generated for you.
      </div>
    );
  return (
    <div className="tbl-w">
      <table className="tbl fh-tbl cmp-tbl" aria-label="Leagues and tournaments">
        <thead>
          <tr>
            <th>Competition</th>
            <th>Format</th>
            <th>Teams</th>
            <th>Fixtures</th>
            <th>Dates</th>
            <th>Status</th>
            <th aria-label="Open" />
          </tr>
        </thead>
        <tbody>
          {groups.map((g) => (
            <tr key={g.key} className="cmp-row" onClick={() => onOpen(g)}>
              <td data-label="Competition">
                {/* One wrapper per cell: on a phone each cell is a label/value pair. */}
                <div>
                  <button
                    className="cmp-name"
                    onClick={(e) => {
                      e.stopPropagation();
                      onOpen(g);
                    }}
                  >
                    {g.name}
                  </button>
                  <div>
                    {g.kind === 'series' ? (
                      // Its own click target: the explainer link must not also open the row.
                      <span onClick={(e) => e.stopPropagation()}>
                        <SeriesOriginPill series={g.series[0] as unknown as Series} />
                      </span>
                    ) : (
                      <span className={`cmp-type ${g.kind}`}>{g.typeLabel}</span>
                    )}
                    {g.series.length > 1 && (
                      <span className="ump-sub"> · {g.series.length} parts</span>
                    )}
                  </div>
                </div>
              </td>
              <td data-label="Format">{g.formatLabel}</td>
              <td data-label="Teams">{g.teams}</td>
              <td data-label="Fixtures">
                <div>
                  {g.fixtures}
                  <div className="ump-sub">{g.played} played</div>
                </div>
              </td>
              <td data-label="Dates">
                {g.firstDate ? `${fmtDay(g.firstDate)} – ${fmtDay(g.lastDate)}` : 'Dates TBC'}
              </td>
              <td data-label="Status">
                <span
                  className={`cmp-status cmp-status-cell ${g.status.toLowerCase().replace(' ', '-')}`}
                >
                  {g.status}
                </span>
              </td>
              <td data-label="" aria-hidden="true">
                <span className="fh-btn-quiet">Open</span>
              </td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}

/* ─── One competition ─── */

type DetailTab = 'fixtures' | 'table' | 'matrix' | 'homeaway' | 'settings';

function CompetitionDetail({
  group,
  activeId,
  onSelectSeries,
  renderFixtures,
  clubs,
  onBack,
  onRegenerate,
  onDeleted,
  onChanged,
  toast,
  renderStatus,
}: CompetitionsPanelProps & {
  group: CompetitionGroup;
  onBack: () => void;
  onRegenerate: () => void;
  onDeleted: () => void;
}) {
  const [tab, setTab] = useState<DetailTab>('fixtures');
  const active = group.series.find((s) => s.id === activeId) ?? group.series[0];
  const clubName = (id: string) => clubs.find((c) => c.id === id)?.name;
  const isKo = active.competition?.role === 'knockout';
  const tabs: Array<[DetailTab, string]> = [
    ['fixtures', 'Fixtures'],
    ...(isKo
      ? ([['table', 'Bracket']] as Array<[DetailTab, string]>)
      : [['table', 'Table'] as [DetailTab, string]]),
    ...(!isKo
      ? ([
          ['matrix', 'Results matrix'],
          ['homeaway', 'Home / away'],
        ] as Array<[DetailTab, string]>)
      : []),
    ...(group.kind === 'competition'
      ? ([['settings', 'Settings']] as Array<[DetailTab, string]>)
      : []),
  ];

  return (
    <div className="cmp-detail">
      <div className="cmp-crumb">
        <button className="fh-link" onClick={onBack}>
          ← All leagues & tournaments
        </button>
      </div>
      <div className="cmp-title-row">
        <div>
          <h2 className="cmp-title">{group.name}</h2>
          <div className="ump-sub">
            {group.typeLabel} · {group.formatLabel} · {group.teams} teams · {group.fixtures}{' '}
            fixtures
            {group.firstDate ? ` · ${fmtDay(group.firstDate)} – ${fmtDay(group.lastDate)}` : ''}
          </div>
        </div>
        <span className="cmp-status-slot">
          {group.series.length > 1 && (
            <span className={`cmp-status ${group.status.toLowerCase().replace(' ', '-')}`}>
              {group.status}
            </span>
          )}
          {renderStatus ? (
            renderStatus()
          ) : group.series.length > 1 ? null : (
            <span className={`cmp-status ${group.status.toLowerCase().replace(' ', '-')}`}>
              {group.status}
            </span>
          )}
        </span>
      </div>
      {group.series.length > 1 && (
        <div className="cmp-parts" role="tablist" aria-label="Part">
          {group.series.map((s) => (
            <button
              key={s.id}
              role="tab"
              aria-selected={s.id === active.id}
              className={`cmp-chip${s.id === active.id ? ' on' : ''}`}
              onClick={() => {
                onSelectSeries(s.id);
                if (s.competition?.role === 'knockout' && (tab === 'matrix' || tab === 'homeaway'))
                  setTab('table');
              }}
            >
              {s.competition?.groupLabel ??
                (s.competition?.role === 'knockout' ? 'Knockout' : s.name)}
              {s.released ? '' : ' · draft'}
            </button>
          ))}
        </div>
      )}
      <div className="fh-tabs cmp-tabs" role="tablist" aria-label="Competition">
        {tabs.map(([k, label]) => (
          <button
            key={k}
            role="tab"
            aria-selected={tab === k}
            className={`fh-tab${tab === k ? ' on' : ''}`}
            onClick={() => setTab(k)}
          >
            {label}
          </button>
        ))}
      </div>
      {tab === 'fixtures' && renderFixtures()}
      {tab === 'table' &&
        (isKo ? (
          <KnockoutView
            series={active}
            group={group}
            clubName={clubName}
            onChanged={onChanged}
            toast={toast}
          />
        ) : (
          <StandingsView series={active} clubName={clubName} />
        ))}
      {tab === 'matrix' && <ResultsMatrixView series={active} clubName={clubName} />}
      {tab === 'homeaway' && <HomeAwayView series={active} clubName={clubName} />}
      {tab === 'settings' && group.meta && (
        <CompetitionSettings
          group={group}
          meta={group.meta}
          onRegenerate={onRegenerate}
          onDeleted={onDeleted}
          onChanged={onChanged}
          toast={toast}
        />
      )}
    </div>
  );
}

function StandingsView({
  series,
  clubName,
}: {
  series: CmpSeries;
  clubName: (id: string) => string | undefined;
}) {
  const names = teamNames(series, clubName);
  const rows = seriesStandings(series, names);
  const pts = series.competition?.points ?? DEFAULT_CRICKET_POINTS;
  const q =
    series.competition?.format.kind === 'groups-knockout'
      ? series.competition.format.qualifiers
      : 0;
  const played = (series.fixtures as CmpFixture[]).filter((f) => f.result).length;
  return (
    <div>
      <div className="tbl-w">
        <table className="tbl cmp-standings" aria-label="League table">
          <thead>
            <tr>
              <th>#</th>
              <th>Team</th>
              <th title="Played">P</th>
              <th title="Won">W</th>
              <th title="Lost">L</th>
              <th title="Tied">T</th>
              <th title="No result">NR</th>
              <th title="Points">Pts</th>
              <th title="Net run rate">NRR</th>
              <th>Form</th>
            </tr>
          </thead>
          <tbody>
            {rows.map((r, i) => (
              <tr key={r.teamId} className={i < q ? 'qualifies' : ''}>
                <td>{i + 1}</td>
                <td className="cmp-team">{r.name}</td>
                <td>{r.played}</td>
                <td>{r.won}</td>
                <td>{r.lost}</td>
                <td>{r.tied}</td>
                <td>{r.noResult}</td>
                <td className="cmp-pts">{r.points}</td>
                <td>{r.nrr === null ? '—' : (r.nrr > 0 ? '+' : '') + r.nrr.toFixed(3)}</td>
                <td>
                  <span className="cmp-form">
                    {r.form.map((f, j) => (
                      <i
                        key={j}
                        className={`f-${f}`}
                        title={{ W: 'Won', L: 'Lost', T: 'Tied', N: 'No result' }[f]}
                      >
                        {f}
                      </i>
                    ))}
                  </span>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
      <p className="fh-note">
        {played
          ? `${played} results in.`
          : 'No results yet — the table fills as results arrive from medicoach.'}{' '}
        Win {pts.win} · Tie {pts.tie} · No result {pts.noResult} · Loss {pts.loss}. Ranked on
        points, then net run rate (a side bowled out counts its full overs), then wins.
        {q ? ` The top ${q} go through to the knockout (highlighted).` : ''}
      </p>
    </div>
  );
}

function ResultsMatrixView({
  series,
  clubName,
}: {
  series: CmpSeries;
  clubName: (id: string) => string | undefined;
}) {
  const names = teamNames(series, clubName);
  const { ids, cells } = resultsMatrix(series, names);
  return (
    <div>
      <p className="fh-note">
        Row = home team · Column = away team · each cell is the result, or when it&apos;s scheduled.
      </p>
      <div className="tbl-w cmp-matrix-wrap">
        <table className="cmp-matrix" aria-label="Results matrix">
          <thead>
            <tr>
              <th>Home ↓ / Away →</th>
              {ids.map((id) => (
                <th key={id} title={names.get(id)}>
                  {names.get(id)}
                </th>
              ))}
            </tr>
          </thead>
          <tbody>
            {ids.map((h) => (
              <tr key={h}>
                <th>{names.get(h)}</th>
                {ids.map((a) => {
                  if (a === h) return <td key={a} className="self" aria-label="—" />;
                  const c = cells.get(`${h}|${a}`);
                  return (
                    <td key={a} className={c ? c.outcome : 'none'}>
                      {c?.label ?? ''}
                    </td>
                  );
                })}
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
}

function HomeAwayView({
  series,
  clubName,
}: {
  series: CmpSeries;
  clubName: (id: string) => string | undefined;
}) {
  const rows = homeAwayBalance(series, teamNames(series, clubName));
  return (
    <div className="tbl-w">
      <table className="tbl cmp-standings" aria-label="Home and away balance">
        <thead>
          <tr>
            <th>Team</th>
            <th>Home</th>
            <th>Away</th>
            <th>Balance</th>
          </tr>
        </thead>
        <tbody>
          {rows.map((r) => (
            <tr key={r.teamId} className={Math.abs(r.home - r.away) > 1 ? 'warn' : ''}>
              <td className="cmp-team">{r.name}</td>
              <td>{r.home}</td>
              <td>{r.away}</td>
              <td>
                {r.home - r.away === 0
                  ? 'Even'
                  : r.home > r.away
                    ? `+${r.home - r.away} home`
                    : `+${r.away - r.home} away`}
              </td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}

function KnockoutView({
  series,
  group,
  clubName,
  onChanged,
  toast,
}: {
  series: CmpSeries;
  group: CompetitionGroup;
  clubName: (id: string) => string | undefined;
  onChanged: () => void;
  toast: (m: string, tone?: string) => void;
}) {
  const [busy, setBusy] = useState(false);
  const [waiting, setWaiting] = useState<string[] | null>(null);
  const names = teamNames(series, clubName);
  for (const s of group.series) for (const [k, v] of teamNames(s, clubName)) names.set(k, v);
  const fixtures = series.fixtures as CmpFixture[];
  const rounds = [...new Set(fixtures.map((f) => f.round ?? 1))].sort((a, b) => a - b);
  const advance = async (allowIncomplete: boolean) => {
    setBusy(true);
    try {
      const r = await api.advanceCompetition(group.meta!.id, allowIncomplete);
      setWaiting(r.waiting);
      toast(
        r.filled
          ? `${r.filled} knockout place${r.filled === 1 ? '' : 's'} filled`
          : 'Nothing to fill yet',
        r.filled ? undefined : 'warn',
      );
      if (r.filled) onChanged();
    } catch (e) {
      toast(errText(e), 'warn');
    } finally {
      setBusy(false);
    }
  };
  return (
    <div>
      {group.kind === 'competition' && (
        <div className="fh-toolbar">
          <div className="ump-sub">
            Places fill from the group tables once every group game is in, and later rounds from
            results.
          </div>
          <div className="fh-toolbar-right">
            <Btn tone="outline" size="sm" disabled={busy} onClick={() => advance(true)}>
              Fill from tables as they stand
            </Btn>
            <Btn tone="ink" size="sm" disabled={busy} onClick={() => advance(false)}>
              {busy ? 'Filling…' : 'Advance knockout'}
            </Btn>
          </div>
        </div>
      )}
      {waiting && waiting.length > 0 && (
        <div className="insights-callout warn" role="note">
          Still waiting: {waiting.join(' · ')}
        </div>
      )}
      <div className="cmp-bracket">
        {rounds.map((r) => (
          <section key={r} aria-label={`Round ${r}`}>
            <h4>
              {r === rounds[rounds.length - 1] && fixtures.filter((f) => f.round === r).length <= 2
                ? 'Final'
                : `Round ${r}`}
            </h4>
            {fixtures
              .filter((f) => (f.round ?? 1) === r)
              .map((f) => (
                <div key={f.id} className="cmp-tie">
                  <div className={f.result?.winner === 'home' ? 'won' : ''}>
                    {sideName(f.home, names, fixtures)} <span>{f.result?.homeScore ?? ''}</span>
                  </div>
                  <div className={f.result?.winner === 'away' ? 'won' : ''}>
                    {sideName(f.away, names, fixtures)} <span>{f.result?.awayScore ?? ''}</span>
                  </div>
                  <div className="ump-sub">
                    {fmtDay(f.date)}
                    {f.time ? ` · ${f.time}` : ''}
                  </div>
                </div>
              ))}
          </section>
        ))}
      </div>
    </div>
  );
}

function CompetitionSettings({
  group,
  meta,
  onRegenerate,
  onDeleted,
  onChanged,
  toast,
}: {
  group: CompetitionGroup;
  meta: CompetitionMeta;
  onRegenerate: () => void;
  onDeleted: () => void;
  onChanged: () => void;
  toast: (m: string, tone?: string) => void;
}) {
  const [name, setName] = useState(meta.name);
  const [pts, setPts] = useState<PointsRules>(meta.points);
  const [busy, setBusy] = useState<null | 'save' | 'delete'>(null);
  const [err, setErr] = useState<string | null>(null);
  const [confirmDelete, setConfirmDelete] = useState(false);
  const released = group.series.some((s) => s.released);
  const hasResults = group.played > 0;
  const save = async () => {
    setBusy('save');
    setErr(null);
    try {
      await api.patchCompetition(meta.id, { name: name.trim(), points: pts });
      toast('Saved');
      onChanged();
    } catch (e) {
      setErr(errText(e));
    } finally {
      setBusy(null);
    }
  };
  const del = async () => {
    setBusy('delete');
    setErr(null);
    try {
      await api.deleteCompetition(meta.id);
      toast(`${meta.name} deleted`);
      onChanged();
      onDeleted();
    } catch (e) {
      setErr(errText(e));
      setBusy(null);
      setConfirmDelete(false);
    }
  };
  return (
    <div className="cmp-settings">
      <section>
        <h3 className="fh-h2">Name and points</h3>
        <div className="fm-grid">
          <label className="fm-field fm-wide">
            Name
            <input value={name} onChange={(e) => setName(e.target.value)} />
          </label>
          {(['win', 'tie', 'noResult', 'loss'] as const).map((k) => (
            <label key={k} className="fm-field">
              {{ win: 'Win', tie: 'Tie', noResult: 'No result', loss: 'Loss' }[k]} points
              <input
                type="number"
                min={0}
                max={20}
                value={pts[k]}
                onChange={(e) => setPts({ ...pts, [k]: Number(e.target.value) })}
              />
            </label>
          ))}
        </div>
        <div className="fm-actions">
          <Btn tone="ink" disabled={busy !== null || !name.trim()} onClick={save}>
            {busy === 'save' ? 'Saving…' : 'Save'}
          </Btn>
        </div>
      </section>
      <section>
        <h3 className="fh-h2">Redo the draw</h3>
        <p className="fh-note">
          Change teams, format, dates or start times and generate the fixtures again. Only while it
          is a draft with no results in.
        </p>
        <Btn tone="outline" disabled={released || hasResults} onClick={onRegenerate}>
          Regenerate fixtures…
        </Btn>
        {(released || hasResults) && (
          <div className="ump-sub" style={{ marginTop: 6 }}>
            {released ? 'Released — recall it first.' : 'Results are in, so the draw is fixed.'}
          </div>
        )}
      </section>
      <section>
        <h3 className="fh-h2">Delete</h3>
        <p className="fh-note">
          Removes every fixture of this competition and the officials appointed to them. A released
          competition has to be recalled first.
        </p>
        {confirmDelete ? (
          <div className="fm-actions" style={{ justifyContent: 'flex-start' }}>
            <Btn tone="outline" onClick={() => setConfirmDelete(false)}>
              Keep it
            </Btn>
            <Btn tone="ink" disabled={busy !== null} onClick={del}>
              {busy === 'delete' ? 'Deleting…' : `Yes, delete ${meta.name}`}
            </Btn>
          </div>
        ) : (
          <Btn tone="outline" disabled={released} onClick={() => setConfirmDelete(true)}>
            Delete {group.typeLabel.toLowerCase()}…
          </Btn>
        )}
        {released && (
          <div className="ump-sub" style={{ marginTop: 6 }}>
            Released — recall it before deleting.
          </div>
        )}
      </section>
      {err && (
        <div className="insights-callout alert fm-error" role="alert">
          {err}
        </div>
      )}
    </div>
  );
}

/* ─── Create / regenerate ─── */

const today = () => new Date(Date.now() + 2 * 3_600_000).toISOString().slice(0, 10);
const newSeed = () => Math.floor(Math.random() * 1_000_000_000);

export function CompetitionDialog({
  mode,
  type: initialType,
  group,
  clubs,
  leagues,
  onClose,
  onDone,
}: {
  mode: 'create' | 'regenerate';
  type: 'league' | 'tournament';
  group?: CompetitionGroup;
  clubs: ClubLike[];
  leagues: LeagueLike[];
  onClose: () => void;
  /** Saved: the competition id, its first series (groups come first) and a toast. */
  onDone: (id: string, firstSeriesId: string, message: string) => void;
}) {
  const meta = group?.meta;
  const first = group?.series[0];
  const [type, setType] = useState<'league' | 'tournament'>(meta?.type ?? initialType);
  const [name, setName] = useState(meta?.name ?? '');
  const [leagueKey, setLeagueKey] = useState<string>(
    typeof first?.leagueKey === 'string' ? first.leagueKey : '',
  );
  const [overs, setOvers] = useState<number>(
    typeof first?.maxOvers === 'number' ? first.maxOvers : 20,
  );
  const [format, setFormat] = useState<CompetitionFormat>(
    meta?.format ??
      (initialType === 'league'
        ? { kind: 'round-robin', legs: 1 }
        : { kind: 'knockout', thirdPlace: false }),
  );
  const [startDate, setStartDate] = useState(meta?.schedule.startDate ?? '');
  const [everyDays, setEveryDays] = useState(meta?.schedule.everyDays ?? 7);
  const [times, setTimes] = useState<string[]>(meta?.schedule.times ?? ['10:00']);
  const [exclude, setExclude] = useState<string[]>(meta?.schedule.excludeDates ?? []);
  const [pts, setPts] = useState<PointsRules>(meta?.points ?? DEFAULT_CRICKET_POINTS);
  const [seed, setSeed] = useState<number | undefined>(meta?.seed);

  // Every team the union has: a club's teams for the chosen league, else the club itself.
  const allTeams = useMemo(() => {
    const out = clubs.flatMap((c) =>
      leagueKey && (c.leagues ?? []).includes(leagueKey)
        ? clubTeamsForLeague(c as never, leagueKey)
        : [
            {
              teamId: c.id,
              clubId: c.id,
              name: c.name,
              venue: c.ground?.venue,
              lat: c.ground?.lat,
              lon: c.ground?.lon,
            },
          ],
    );
    return out.sort((a, b) => a.name.localeCompare(b.name));
  }, [clubs, leagueKey]);
  const [picked, setPicked] = useState<Set<string>>(
    () =>
      new Set(
        group
          ? group.series.flatMap((s) => s.participants?.map((p) => p.teamId) ?? s.teams ?? [])
          : [],
      ),
  );
  const pickLeague = (key: string) => {
    setLeagueKey(key);
    if (key && !name) setName(leagues.find((l) => l.key === key)?.label ?? '');
    if (key)
      setPicked(
        new Set(
          clubs
            .filter((c) => (c.leagues ?? []).includes(key))
            .flatMap((c) => clubTeamsForLeague(c as never, key).map((t) => t.teamId)),
        ),
      );
  };
  const [preview, setPreview] = useState<api.CompetitionPreview | null>(null);
  const [busy, setBusy] = useState<null | 'preview' | 'save'>(null);
  const [err, setErr] = useState<string | null>(null);

  const body = (s = seed): api.CompetitionSpecBody => ({
    ...(preview?.id || meta?.id ? { id: meta?.id ?? preview!.id } : {}),
    type,
    name: name.trim(),
    ...(leagueKey ? { leagueKey } : {}),
    overs,
    teams: allTeams.filter((t) => picked.has(t.teamId)),
    format,
    schedule: {
      startDate,
      everyDays,
      times: times.filter(Boolean),
      excludeDates: exclude.filter(Boolean),
    },
    points: pts,
    ...(s !== undefined ? { seed: s } : {}),
  });
  const runPreview = async (s = seed) => {
    setBusy('preview');
    setErr(null);
    try {
      setPreview(await api.previewCompetition(body(s)));
    } catch (e) {
      setPreview(null);
      setErr(errText(e));
    } finally {
      setBusy(null);
    }
  };
  const save = async () => {
    setBusy('save');
    setErr(null);
    try {
      const done =
        mode === 'regenerate'
          ? await api.regenerateCompetition(meta!.id, body())
          : await api.createCompetition(body());
      onDone(
        done.id,
        String(done.series[0]?.id ?? done.id),
        mode === 'regenerate' ? 'Fixtures regenerated' : `${name.trim()} created as a draft`,
      );
    } catch (e) {
      setErr(errText(e));
      setBusy(null);
    }
  };
  // Any change after a preview invalidates it.
  const touch =
    <T,>(fn: (v: T) => void) =>
    (v: T) => {
      fn(v);
      setPreview(null);
    };

  const teamsPicked = allTeams.filter((t) => picked.has(t.teamId)).length;
  return (
    <Modal
      eyebrow={mode === 'regenerate' ? 'Regenerate fixtures' : 'Leagues & tournaments'}
      title={
        mode === 'regenerate'
          ? `Redo the draw · ${meta?.name}`
          : type === 'league'
            ? 'Create a league'
            : 'Create a tournament'
      }
      maxWidth={880}
      onClose={onClose}
      confirmClose={!busy}
    >
      <div className="cmp-dialog">
        {mode === 'create' && (
          <div className="cmp-seg" role="radiogroup" aria-label="Type">
            {(['league', 'tournament'] as const).map((t) => (
              <button
                key={t}
                role="radio"
                aria-checked={type === t}
                className={type === t ? 'on' : ''}
                onClick={() => {
                  setType(t);
                  setFormat(
                    t === 'league'
                      ? { kind: 'round-robin', legs: 1 }
                      : { kind: 'knockout', thirdPlace: false },
                  );
                  setPreview(null);
                }}
              >
                {t === 'league'
                  ? 'League — everyone plays everyone'
                  : 'Tournament — knockout, or groups then knockout'}
              </button>
            ))}
          </div>
        )}
        <div className="fm-grid">
          <label className="fm-field">
            Name
            <input
              value={name}
              placeholder={type === 'league' ? 'e.g. Premier League T20' : 'e.g. Kingsmead Cup'}
              onChange={(e) => touch(setName)(e.target.value)}
            />
          </label>
          <label className="fm-field">
            League in the catalogue (optional)
            <select
              value={leagueKey}
              onChange={(e) => (pickLeague(e.target.value), setPreview(null))}
            >
              <option value="">Not linked</option>
              {leagues.map((l) => (
                <option key={l.key} value={l.key}>
                  {l.label}
                </option>
              ))}
            </select>
          </label>
          <label className="fm-field">
            Overs per side
            <input
              type="number"
              min={1}
              max={200}
              value={overs}
              onChange={(e) => touch(setOvers)(Number(e.target.value))}
            />
          </label>
          {type === 'league' && format.kind === 'round-robin' && (
            <label className="fm-field">
              Play each other
              <select
                value={format.legs}
                onChange={(e) =>
                  touch(setFormat)({ kind: 'round-robin', legs: Number(e.target.value) as 1 | 2 })
                }
              >
                <option value={1}>Once</option>
                <option value={2}>Twice (home and away)</option>
              </select>
            </label>
          )}
          {type === 'tournament' && (
            <label className="fm-field">
              Format
              <select
                value={format.kind}
                onChange={(e) =>
                  touch(setFormat)(
                    e.target.value === 'knockout'
                      ? { kind: 'knockout', thirdPlace: false }
                      : {
                          kind: 'groups-knockout',
                          groups: 2,
                          qualifiers: 2,
                          legs: 1,
                          thirdPlace: false,
                        },
                  )
                }
              >
                <option value="knockout">Knockout</option>
                <option value="groups-knockout">Groups, then knockout</option>
              </select>
            </label>
          )}
          {format.kind === 'groups-knockout' && (
            <>
              <label className="fm-field">
                Groups
                <select
                  value={format.groups}
                  onChange={(e) => touch(setFormat)({ ...format, groups: Number(e.target.value) })}
                >
                  {[2, 3, 4, 6, 8].map((n) => (
                    <option key={n} value={n}>
                      {n}
                    </option>
                  ))}
                </select>
              </label>
              <label className="fm-field">
                Through to the knockout
                <select
                  value={format.qualifiers}
                  onChange={(e) =>
                    touch(setFormat)({ ...format, qualifiers: Number(e.target.value) as 1 | 2 })
                  }
                >
                  <option value={1}>Group winners</option>
                  <option value={2}>Top two per group</option>
                </select>
              </label>
            </>
          )}
          {format.kind !== 'round-robin' && (
            <label className="fm-radio fm-wide">
              <input
                type="checkbox"
                checked={!!format.thirdPlace}
                onChange={(e) =>
                  touch(setFormat)({ ...format, thirdPlace: e.target.checked } as CompetitionFormat)
                }
              />
              Play a third-place game
            </label>
          )}
        </div>

        <fieldset className="fm-ground cmp-teams">
          <legend>
            Teams · {teamsPicked} picked
            <button
              className="fh-link"
              onClick={() => (setPicked(new Set(allTeams.map((t) => t.teamId))), setPreview(null))}
            >
              All
            </button>
            <button className="fh-link" onClick={() => (setPicked(new Set()), setPreview(null))}>
              None
            </button>
          </legend>
          <div className="cmp-team-grid">
            {allTeams.map((t) => (
              <label key={t.teamId} className="fm-radio">
                <input
                  type="checkbox"
                  checked={picked.has(t.teamId)}
                  onChange={(e) => {
                    const next = new Set(picked);
                    if (e.target.checked) next.add(t.teamId);
                    else next.delete(t.teamId);
                    setPicked(next);
                    setPreview(null);
                  }}
                />
                {t.name}
              </label>
            ))}
          </div>
        </fieldset>

        <div className="fm-grid">
          <label className="fm-field">
            First round
            <input
              type="date"
              value={startDate}
              min={mode === 'create' ? today() : undefined}
              onChange={(e) => touch(setStartDate)(e.target.value)}
            />
          </label>
          <label className="fm-field">
            Then every
            <select value={everyDays} onChange={(e) => touch(setEveryDays)(Number(e.target.value))}>
              <option value={7}>Week</option>
              <option value={14}>Two weeks</option>
              <option value={1}>Day (festival)</option>
              <option value={3}>Three days</option>
            </select>
          </label>
          <label className="fm-field">
            Start times
            <span className="cmp-times">
              {times.map((t, i) => (
                <input
                  key={i}
                  type="time"
                  aria-label={`Start time ${i + 1}`}
                  value={t}
                  onChange={(e) =>
                    touch(setTimes)(times.map((x, j) => (j === i ? e.target.value : x)))
                  }
                />
              ))}
              {times.length < 2 && (
                <button className="fh-add" onClick={() => touch(setTimes)([...times, '13:30'])}>
                  + Second time
                </button>
              )}
              {times.length > 1 && (
                <button className="fh-link" onClick={() => touch(setTimes)(times.slice(0, 1))}>
                  One time only
                </button>
              )}
            </span>
          </label>
          <label className="fm-field">
            Skip these dates
            <input
              placeholder="e.g. 2026-12-19, 2026-12-26"
              value={exclude.join(', ')}
              onChange={(e) => touch(setExclude)(e.target.value.split(/[,\s]+/).filter(Boolean))}
            />
          </label>
        </div>

        <details className="cmp-points">
          <summary>
            Points: win {pts.win} · tie {pts.tie} · no result {pts.noResult} · loss {pts.loss}
          </summary>
          <div className="fm-grid">
            {(['win', 'tie', 'noResult', 'loss'] as const).map((k) => (
              <label key={k} className="fm-field">
                {{ win: 'Win', tie: 'Tie', noResult: 'No result', loss: 'Loss' }[k]}
                <input
                  type="number"
                  min={0}
                  max={20}
                  value={pts[k]}
                  onChange={(e) => touch(setPts)({ ...pts, [k]: Number(e.target.value) })}
                />
              </label>
            ))}
          </div>
        </details>

        {preview && <PreviewBlock preview={preview} clubs={clubs} allTeams={allTeams} />}
        {err && (
          <div className="insights-callout alert fm-error" role="alert">
            {err}
          </div>
        )}
      </div>
      <div className="fm-actions">
        <Btn tone="outline" onClick={onClose} disabled={!!busy}>
          Cancel
        </Btn>
        <Btn
          tone="outline"
          disabled={!!busy}
          onClick={() => {
            const s = newSeed();
            setSeed(s);
            runPreview(s);
          }}
        >
          Randomise draw
        </Btn>
        <Btn tone="outline" disabled={!!busy} onClick={() => runPreview()}>
          {busy === 'preview' ? 'Generating…' : preview ? 'Preview again' : 'Preview fixtures'}
        </Btn>
        <Btn
          tone="ink"
          disabled={!!busy || !preview}
          onClick={save}
          title={preview ? undefined : 'Preview the fixtures first'}
        >
          {busy === 'save'
            ? 'Saving…'
            : mode === 'regenerate'
              ? 'Replace the fixtures'
              : `Create ${type} (draft)`}
        </Btn>
      </div>
    </Modal>
  );
}

function PreviewBlock({
  preview,
  allTeams,
}: {
  preview: api.CompetitionPreview;
  clubs: ClubLike[];
  allTeams: Array<{ teamId: string; name: string }>;
}) {
  const names = new Map(allTeams.map((t) => [t.teamId, t.name]));
  const all = preview.series.flatMap((s) =>
    (s.fixtures as CmpFixture[]).map((f) => ({
      ...f,
      part:
        (s as CmpSeries).competition?.groupLabel ??
        ((s as CmpSeries).competition?.role === 'knockout' ? 'Knockout' : ''),
    })),
  );
  const dates = [...new Set(all.map((f) => f.date ?? ''))].sort();
  return (
    <section className="cmp-preview" aria-label="Fixture preview">
      <div className="cmp-preview-sum">
        <strong>{preview.summary.fixtures} fixtures</strong> over {preview.summary.rounds} playing
        dates · {fmtDay(preview.summary.firstDate)} – {fmtDay(preview.summary.lastDate)}
      </div>
      {preview.warnings.map((w) => (
        <div key={w} className="insights-callout warn" role="note">
          {w}
        </div>
      ))}
      {preview.clashes.length > 0 && (
        <div className="insights-callout warn" role="note">
          <strong>Ground double-bookings to sort out before release:</strong>
          <ul>
            {preview.clashes.slice(0, 6).map((c) => (
              <li key={c}>{c}</li>
            ))}
          </ul>
          {preview.clashes.length > 6 && <div>…and {preview.clashes.length - 6} more.</div>}
        </div>
      )}
      <div className="cmp-preview-rounds">
        {dates.map((d) => (
          <div key={d}>
            <div className="fh-day-sub">{fmtDay(d)}</div>
            {all
              .filter((f) => f.date === d)
              .map((f) => (
                <div key={`${f.part}-${f.id}`} className="cmp-preview-fx">
                  <span>{f.time ?? ''}</span>
                  <span>
                    {sideName(f.home, names, all)} v {sideName(f.away, names, all)}
                  </span>
                  {f.part && <span className="ump-sub">{f.part}</span>}
                </div>
              ))}
          </div>
        ))}
      </div>
    </section>
  );
}
